### ISSUE TITLE
Hackage Revision Request: base-compat-batteries-0.12.2 to allow OneTuple < 0.5

### ISSUE THREAD

**Issue by sternenseemann** [haskell-compat/base-compat#91]
This would help us out in nixpkgs where we now follow Stackage LTS 21 for the versions of base-compat-batteries and OneTuple to use which are 0.12.* and 0.4.*, respectively. For GHCs < 9.0 OneTuple is required to build base-compat-batteries and we run into this problem. Using the two versions together seems to work, so the bound on hackage could be loosened.

**Comment by RyanGlScott** [comment]
Hm. I'm not sure if simply lifting the `OneTuple` upper version bounds in `base-compat-batteries-0.12.2` would be wise, since that could lead to a conditional API. This is because in `OneTuple-0.3.*` and earlier, `Solo`'s data constructor is named `Solo`, but in `OneTuple-0.4.*`, `Solo`'s data constructor is named `MkSolo`. This can be seen in this program:

```hs
#!/usr/bin/env cabal
{- cabal:
build-depends: base, base-compat-batteries==0.12.2, OneTuple==0.3.*
-}
{- project:
with-compiler: ghc-8.10
-}
{-# LANGUAGE PackageImports #-}
module Main (main) where

import "base-compat-batteries" Data.Tuple.Compat (Solo(..))

f :: a -> Solo a
f = MkSolo

main :: IO ()
main = print (f ())
```

Note that I have intentionally set up the project information to ensure that when this program imports `Data.Tuple.Compat`, it will use the `Solo` that is re-exported by `OneTuple-0.3.*`. (This is why I use GHC 8.10, as newer GHCs would bypass `OneTuple`.) This program will fail to compile, since `OneTuple-0.3.*` doesn't define `MkSolo`:

```
$ ./Foo1.hs

C:\msys64\home\winferno\Foo1.hs:14:5: error:
    * Data constructor not in scope: MkSolo :: a -> Solo a
    * Perhaps you meant `Solo' (imported from Data.Tuple.Compat)
   |
14 | f = MkSolo
   |     ^^^^^^
```

On the other hand, if I tweak the program such that `base-compat-batteries-0.12.2` is allowed to build with `OneTuple-0.4.*`:

```hs
#!/usr/bin/env cabal
{- cabal:
build-depends: base, base-compat-batteries==0.12.2, OneTuple==0.4.*
-}
{- project:
with-compiler: ghc-8.10
allow-newer: base-compat-batteries:OneTuple
-}
-- same as before...
```

Then the program _will_ compile, with no changes made to the code!

```
$ ./Foo2.hs
MkSolo ()
```

This could lead to confusing scenarios. On the other hand, the situation is arguably _already_ confusing, since you would get the same thing if you switched from GHC 8.10 to GHC 9.6:

```hs
#!/usr/bin/env cabal
{- cabal:
build-depends: base, base-compat-batteries==0.12.2
-}
{- project:
with-compiler: ghc-9.6
-}
-- same as before
```
```
$ ./Foo3.hs
MkSolo ()
```

**Comment by RyanGlScott** [comment]
An alternative would be to make a `base-compat-batteries-0.12.*` point release that tightens up the exports in `Data.Tuple.Compat` a bit. Currently, the `base-compat-batteries-0.12.2` release just re-exports whatever `Solo` data constructor happens to be in scope, regardless of whether it is named `Solo` or `MkSolo`:

https://github.com/haskell-compat/base-compat/blob/95eaf2e1363f574e763434ad4531652aeb85c978/base-compat-batteries/src/Data/Tuple/Compat.hs#L2-L3

We could change that to only re-export the `Solo` data constructor (or pattern synonym, depending on what versions of `base`/`OneTuple` we use).

**Comment by RyanGlScott** [comment]
I've submitted #92, which makes the necessary code changes to prepare for a `base-compat-batteries-0.12.3` minor release. @sternenseemann, can you check that this works for your needs?

**Comment by RyanGlScott** [comment]
I've uploaded [`base-compat-0.12.3`](https://hackage.haskell.org/package/base-compat-0.12.3) and [`base-compat-batteries-0.12.3`](https://hackage.haskell.org/package/base-compat-batteries-0.12.3) to Hackage, which contain the changes from #92.

**Comment by sternenseemann** [comment]
Thanks!
