### ISSUE TITLE
batteries: incorrect lower bounds

### ISSUE THREAD

**Issue by phadej** [haskell-compat/base-compat#47]
`trustee matrix . --constraint='semigroups==0.16.2.2'`

```
                               8.4.1  8.2.2  8.0.2  7.10.3  7.8.4  7.6.3  7.4.2  7.2.2  7.0.4
base-compat-batteries-0.10.0/  OK     OK     NO-IP  FAIL    FAIL   FAIL   FAIL   FAIL   FAIL
```

```
src/Data/Semigroup/Compat.hs:4:5: Not in scope: ‘stimesMonoid’

src/Data/Semigroup/Compat.hs:5:5: Not in scope: ‘stimesIdempotent’

src/Data/Semigroup/Compat.hs:6:5:
    Not in scope: ‘stimesIdempotentMonoid’

src/Data/Semigroup/Compat.hs:7:5: Not in scope: ‘mtimesDefault’
```

---

I'll make revision, but should we have a new release too, with stricter lower-bounds, e.g. for `semigroups-0.18.4` changelog says

> Backport Semigroup instances for Data.Ord.Down and strict ST, which were added in base-4.11.

which IMO is important backport-compat-wise.

Similarly `tagged-` http://hackage.haskell.org/package/tagged-0.8.5/changelog

**Comment by RyanGlScott** [comment]
OK. Can we do both things at once and make a revision requiring 0.18.4 as the lower bounds?

**Comment by phadej** [comment]
@RyanGlScott Well, it would invalidate few build-plans if someone was super quick taking `-batteries` into use :), so it's up to you.

**Comment by phadej** [comment]
Updated: I swept all dependencies with `semigroups >= 0.17`, the whole "matrix" is green,
except `bifunctors` fail to build with GHC 7.2.2 (5.4.1 .. 5.5.1 (4)). I think we cannot do anything for that.

I'd revise `base-compat-batteries-0.10.0` with `semigroups >=0.17` and make a `base-compat-batteries-0.10.1` (and `base-compat`) with `Data.List.NonEmpty.Compat` and stricter (`semigroups >=0.18.4`) bound.
